#!/usr/bin/env python3
"""Regenerate the "Questions verbatim" appendix in each findings document.

The proof files' moduledocs are the single source of truth for question wording;
this copies them into the docs so the two can never drift.

    python3 sync_readme_questions.py

README.md          <- test/proofs/          (candidate answered correctly)
OTHER_DISPUTES.md  <- test/answered_wrong/  (candidate did not)
"""
import re, glob, os

START = "<!-- BEGIN QUESTIONS (generated by sync_readme_questions.py) -->"
END = "<!-- END QUESTIONS -->"


def field(body, name):
    m = re.search(r"^\s*%s\s*:\s*(.+)$" % name, body, re.M)
    return m.group(1).strip() if m else "?"


def question_block(body):
    """Lines between 'Question text:' and the Candidate/Exam-key line."""
    out, on = [], False
    for line in body.split("\n"):
        if re.match(r"\s*Question text:", line):
            on = True
            continue
        if on and re.match(r"\s*(Candidate|Exam key|Exam says)\s*:", line):
            break
        if on:
            out.append(line)
    while out and not out[0].strip():
        out.pop(0)
    while out and not out[-1].strip():
        out.pop()
    pads = [len(l) - len(l.lstrip()) for l in out if l.strip()]
    n = min(pads) if pads else 0
    return "\n".join(l[n:] if l.strip() else "" for l in out)


def collect(pattern):
    rows = []
    for f in sorted(glob.glob(pattern)):
        m = re.search(r'@moduledoc """\n(.*?)\n  """', open(f).read(), re.S)
        if not m or "Question text:" not in m.group(1):
            continue  # e.g. the format-example file, which is not a question
        body = m.group(1)
        rows.append({
            "file": f,
            "qnum": int(re.search(r"q(\d+)_", os.path.basename(f)).group(1)),
            "section": field(body, "Section"),
            "question": field(body, "Question"),
            "extid": field(body, "External ID"),
            "text": question_block(body),
            "key": field(body, "Exam key") if "Exam key" in body else field(body, "Exam says"),
            "candidate": field(body, "Candidate"),
            "reality": field(body, "Reality"),
        })
    return rows


def render(rows):
    parts = [START, "", "## Questions verbatim", "",
             "Copied from the proof files' moduledocs — the wording there is the source",
             "of truth. Regenerate with `python3 sync_readme_questions.py`.", ""]
    for r in sorted(rows, key=lambda r: r["qnum"]):
        key = r["key"] if r["key"] != "?" else "_not captured on the results screen — inferred_"
        parts += [
            "### Q%d — Section %s" % (r["qnum"], r["section"]),
            "",
            "`External ID: %s` · Question %s · [proof](%s)" % (r["extid"], r["question"], r["file"]),
            "",
            "```text", r["text"], "```", "",
            "**Exam key:** %s  " % key,
            "**Candidate:** %s  " % r["candidate"],
            "**Reality:** %s" % r["reality"],
            "",
        ]
    parts.append(END)
    return "\n".join(parts)


def sync(doc, pattern):
    rows = collect(pattern)
    gen = render(rows)
    txt = open(doc).read()
    if START in txt and END in txt:
        txt = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: gen, txt, flags=re.S)
    else:
        txt = txt.rstrip() + "\n\n---\n\n" + gen + "\n"
    open(doc, "w").write(txt)
    print("synced %d questions into %s" % (len(rows), doc))


if __name__ == "__main__":
    sync("README.md", "test/proofs/s*.exs")
    sync("OTHER_DISPUTES.md", "test/answered_wrong/*.exs")
