#!/usr/bin/env python3
"""Regenerate README.md's "Questions verbatim" appendix from the proof files.

The test moduledocs are the single source of truth for question wording; this
copies them into the README so the two can never drift. Run after adding or
editing a proof:  python3 sync_readme_questions.py
"""
import re, glob, os

START = "<!-- BEGIN QUESTIONS (generated by sync_readme_questions.py) -->"
END = "<!-- END QUESTIONS -->"

def field(body, name):
    m = re.search(r"^\s*%s\s*:\s*(.+)$" % name, body, re.M)
    return m.group(1).strip() if m else "?"

def block(body, start_pat, stop_pat):
    lines = body.split("\n")
    out, on = [], False
    for l in lines:
        if re.match(start_pat, l):
            on = True
            continue
        if on and re.match(stop_pat, l):
            break
        if on:
            out.append(l)
    while out and not out[0].strip():
        out.pop(0)
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out)

def dedent(text):
    lines = [l for l in text.split("\n")]
    pads = [len(l) - len(l.lstrip()) for l in lines if l.strip()]
    n = min(pads) if pads else 0
    return "\n".join(l[n:] if l.strip() else "" for l in lines)

rows = []
for f in sorted(glob.glob("test/proofs/s*.exs")):
    body = re.search(r'@moduledoc """\n(.*?)\n  """', open(f).read(), re.S).group(1)
    qnum = int(re.search(r"q(\d+)_", os.path.basename(f)).group(1))
    rows.append({
        "file": f,
        "qnum": qnum,
        "section": field(body, "Section"),
        "question": field(body, "Question"),
        "extid": field(body, "External ID"),
        "text": dedent(block(body, r"\s*Question text:", r"\s*(Candidate|Exam key|Exam says)\s*:")),
        "candidate": field(body, "Candidate"),
        "key": field(body, "Exam key") if "Exam key" in body else field(body, "Exam says"),
        "reality": field(body, "Reality"),
    })

parts = [START, "", "## Questions verbatim", "",
         "Copied from the proof files' moduledocs — the wording there is the source of",
         "truth. Regenerate with `python3 sync_readme_questions.py`.", ""]
for r in sorted(rows, key=lambda r: r["qnum"]):
    parts += [
        "### Q%d — Section %s" % (r["qnum"], r["section"]),
        "",
        "`External ID: %s` · Question %s · [proof](%s)" % (r["extid"], r["question"], r["file"]),
        "",
        "```text",
        r["text"],
        "```",
        "",
        "**Exam key:** %s  " % (r["key"] if r["key"] != "?"
                                 else "_not captured on the results screen — inferred_"),
        "**Candidate:** %s  " % r["candidate"],
        "**Reality:** %s" % r["reality"],
        "",
    ]
parts.append(END)
gen = "\n".join(parts)

readme = open("README.md").read()
if START in readme and END in readme:
    readme = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: gen, readme, flags=re.S)
else:
    anchor = "## Filing notes"
    readme = readme.replace(anchor, gen + "\n\n---\n\n" + anchor)
open("README.md", "w").write(readme)
print("synced %d questions into README.md" % len(rows))
